<?php

namespace App\Http\Requests;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\ValidationException;


class UserSignupRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'name' => 'required|string|min:3' ,
            'email' => 'required|email|unique:users,email',
            'phone' => 'required|digits:10|unique:users,phone' ,
            'password' => 'required|min:6'

        ];
    }

    protected function failedValidation(Validator $validator)
    {

        // parent::failedValidation($validator); // TODO: Change the autogenerated stub
        throw new ValidationException($validator, (new \App\Http\Responses\Response)->Validation([], $validator->errors()));

    }
}
